import type { Metadata } from "next";
import {  Oxygen } from "next/font/google";
import "./globals.css";
import Navbar from "./(HomePage)/_components/navbar";

const oxygen = Oxygen({ subsets: ["latin"], weight: ["300", "400", "700"]  });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={oxygen.className} >
		<Navbar />
		{children}
	  </body>
    </html>
  );
}
